name: My first Github Workflow
on: [push]
jobs:
    Test-github-actions:
        runs-on: ubuntu-latest
        steps:
            - run: docker --version
            - run: python --version
            - run: pylint app.py
            - run: docker build --tag testing-app .
            - uses: actions/checkout@v3            
